/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.indizen.fjpiqueras.kafka.ejercicio4.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Empleado schema */
@org.apache.avro.specific.AvroGenerated
public class Empleado extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4407936463957608255L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Empleado\",\"namespace\":\"com.indizen.fjpiqueras.kafka.ejercicio4.avro\",\"doc\":\"Empleado schema\",\"fields\":[{\"name\":\"dni\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"doc\":\"Nombre del empleado\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Empleado> ENCODER =
      new BinaryMessageEncoder<Empleado>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Empleado> DECODER =
      new BinaryMessageDecoder<Empleado>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Empleado> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Empleado> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Empleado>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Empleado to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Empleado from a ByteBuffer. */
  public static Empleado fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Nombre del empleado */
  @Deprecated public java.lang.String dni;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Empleado() {}

  /**
   * All-args constructor.
   * @param dni Nombre del empleado
   */
  public Empleado(java.lang.String dni) {
    this.dni = dni;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return dni;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: dni = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'dni' field.
   * @return Nombre del empleado
   */
  public java.lang.String getDni() {
    return dni;
  }

  /**
   * Sets the value of the 'dni' field.
   * Nombre del empleado
   * @param value the value to set.
   */
  public void setDni(java.lang.String value) {
    this.dni = value;
  }

  /**
   * Creates a new Empleado RecordBuilder.
   * @return A new Empleado RecordBuilder
   */
  public static com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder newBuilder() {
    return new com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder();
  }

  /**
   * Creates a new Empleado RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Empleado RecordBuilder
   */
  public static com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder newBuilder(com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder other) {
    return new com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder(other);
  }

  /**
   * Creates a new Empleado RecordBuilder by copying an existing Empleado instance.
   * @param other The existing instance to copy.
   * @return A new Empleado RecordBuilder
   */
  public static com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder newBuilder(com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado other) {
    return new com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder(other);
  }

  /**
   * RecordBuilder for Empleado instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Empleado>
    implements org.apache.avro.data.RecordBuilder<Empleado> {

    /** Nombre del empleado */
    private java.lang.String dni;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.dni)) {
        this.dni = data().deepCopy(fields()[0].schema(), other.dni);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Empleado instance
     * @param other The existing instance to copy.
     */
    private Builder(com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.dni)) {
        this.dni = data().deepCopy(fields()[0].schema(), other.dni);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'dni' field.
      * Nombre del empleado
      * @return The value.
      */
    public java.lang.String getDni() {
      return dni;
    }

    /**
      * Sets the value of the 'dni' field.
      * Nombre del empleado
      * @param value The value of 'dni'.
      * @return This builder.
      */
    public com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder setDni(java.lang.String value) {
      validate(fields()[0], value);
      this.dni = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'dni' field has been set.
      * Nombre del empleado
      * @return True if the 'dni' field has been set, false otherwise.
      */
    public boolean hasDni() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'dni' field.
      * Nombre del empleado
      * @return This builder.
      */
    public com.indizen.fjpiqueras.kafka.ejercicio4.avro.Empleado.Builder clearDni() {
      dni = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Empleado build() {
      try {
        Empleado record = new Empleado();
        record.dni = fieldSetFlags()[0] ? this.dni : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Empleado>
    WRITER$ = (org.apache.avro.io.DatumWriter<Empleado>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Empleado>
    READER$ = (org.apache.avro.io.DatumReader<Empleado>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
